#!/usr/bin/env bash

# shellcheck disable=SC2086
# shellcheck disable=SC2223

set -euo pipefail

: "${STOS_VERSION?= required}"
: "${ETCD_OPERATOR_VERSION?= required}"

root="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

TMPDIR="$(mktemp -d)"
function cleanup() {
    { set +xe; } >/dev/null 2>&1
    cd "$root"
    rm -rf -- "$TMPDIR"
    if [[ -n "${TMP_STOS_CLUSTER:-}" ]]; then
        rm -f -- "${TMP_STOS_CLUSTER:-}"
    fi
}
trap cleanup EXIT

kargs=( --dry-run --stos-version=develop --etcd-operator-version=develop )

cd "$TMPDIR/"
set -x

# Run install --dry-run command and move output to tmpdir
kubectl storageos install "${kargs[@]}" --k8s-version=v1.22.0 --etcd-endpoints=storageos.etcd:2379
# Fetch operator-manifests and store in temp dir
docker run "storageos/operator-manifests:${STOS_VERSION}" > "${TMPDIR}/storageos-operator.yaml"
# Compare storageos manifests generated by dry-run with test data
diff "${TMPDIR}/storageos-operator.yaml" "${TMPDIR}/storageos-dry-run/"*-storageos-operator.yaml
diff "$root/test-data/storageos-cluster.yaml" "${TMPDIR}/storageos-dry-run/"*-storageos-cluster.yaml
rm -rf storageos-dry-run

#  Run install --dry-run command and move output to tmpdir
kubectl storageos install "${kargs[@]}" --k8s-version=v1.22.0 --include-etcd --etcd-storage-class=standard --etcd-topology-key=topology.kubernetes.io/zone
# Fetch etcd-operator manifest
docker run "storageos/etcd-cluster-operator-manifests:${ETCD_OPERATOR_VERSION}" > "${TMPDIR}/storageos-etcd-cluster-operator.yaml"
# Compare etcd manifests generated by dry-run with test data
diff "${TMPDIR}/storageos-etcd-cluster-operator.yaml" "${TMPDIR}/storageos-dry-run/"*-etcd-operator.yaml
diff "$root/test-data/etcd-cluster.yaml" "${TMPDIR}/storageos-dry-run/"*-etcd-cluster.yaml
rm -rf storageos-dry-run

#  Run install --dry-run command and move output to tmpdir
kubectl storageos install "${kargs[@]}" --k8s-version=v1.22.0-gke.0 --etcd-endpoints=storageos-etcd.storageos-etcd:2379
# Compare resource-quota manifest generated by dry-run with test data
diff "$root/test-data/resource-quota.yaml" "${TMPDIR}/storageos-dry-run/"*-resource-quota.yaml
rm -rf storageos-dry-run

#  Run install --dry-run command and move output to tmpdir
kubectl storageos install "${kargs[@]}" --k8s-version=v1.22.0 --enable-portal-manager --portal-api-url=www.test.com --portal-tenant-id=storageos --portal-client-id=storageos --portal-secret=storageos --etcd-endpoints=storageos-etcd.storageos-etcd:2379
# Fetch portal-configmap
wget -q https://github.com/storageos/kubectl-storageos/releases/download/v1.0.0/configmap-storageos-portal-manager.yaml -P "${TMPDIR}/"
# Compare portal manifests generated by dry-run with test data
diff "$root/test-data/storageos-portal-client.yaml" "${TMPDIR}/storageos-dry-run/"*-storageos-portal-client.yaml
diff "${TMPDIR}/configmap-storageos-portal-manager.yaml" "${TMPDIR}/storageos-dry-run/"*-storageos-portal-configmap.yaml
rm -rf storageos-dry-run

#  Run install --dry-run command and move output to tmpdir
TMP_STOS_CLUSTER="$(mktemp)"
kubectl storageos install "${kargs[@]}" --k8s-version=v1.22.0 --etcd-endpoints=storageos.etcd:2379 --enable-metrics=true
grep --no-filename -A 1 '  metrics:$' "$TMPDIR"/storageos-dry-run/*storageos-cluster.yaml | tail -n 1 | diff <(printf '    enabled: true\n') -
cp -a "$TMPDIR"/storageos-dry-run/*storageos-cluster.yaml "$TMP_STOS_CLUSTER"
rm -rf storageos-dry-run

# make sure that the metrics-enabled settings are preserved
kubectl storageos install "${kargs[@]}" --k8s-version=v1.22.0 --etcd-endpoints=storageos.etcd:2379 --stos-cluster-yaml="$TMP_STOS_CLUSTER"
grep --no-filename -A 1 '  metrics:$' "$TMPDIR"/storageos-dry-run/*storageos-cluster.yaml | tail -n 1 | diff <(printf '    enabled: true\n') -
rm -rf storageos-dry-run

kubectl storageos install "${kargs[@]}" --k8s-version=v1.22.0 --etcd-endpoints=storageos.etcd:2379 --stos-cluster-yaml="$TMP_STOS_CLUSTER" --enable-metrics=false
# make sure the --enable-metrics flag overrides the config
grep --no-filename -A 1 '  metrics:$' "$TMPDIR"/storageos-dry-run/*storageos-cluster.yaml | tail -n 1 | diff <(printf '    enabled: false\n') -
rm -rf storageos-dry-run

echo "Dry run test completed succesfully!"
