apiVersion: storageos.com/v1
kind: KubectlStorageOSConfig
metadata:
  name: kubectlstorageosconfig-sample
spec:
  install:
    storageOSOperatorNamespace: storageos-operator
    storageOSClusterNamespace: storageos-cluster
    etcdNamespace: storageos-etcd-system  
    storageOSOperatorYaml: /path/to/storageos-operator.yaml     
    storageOSClusterYaml: /path/to/storageos-cluster.yaml 
    etcdOperatorYaml: /path/to/etcd-operator.yaml 
    etcdClusterYaml: /path/to/etcd-cluster.yaml
    skipEtcd: false
    etcdEndpoints: "<etcd-endpoints>"
    storageClassName: standard
  uninstall:
    storageOSOperatorNamespace: storageos-operator
    storageOSClusterNamespace: storageos-cluster
    etcdNamespace: storageos-etcd-system  
    skipEtcd: false 
