---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  skip-files: zz_generated*
  timeout: 3m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
      - dupl
      - gosec
      - goconst
    - path: cmd/plugin/cli
      linters:
      - errcheck
    
linters:
  disable: 
    - typecheck
  enable:
    - nilerr
    - whitespace
    - gofmt
    - misspell

linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    # report about shadowed variables
    check-shadowing: false
  gosimple:
    checks: [ "-S1019" ]     
