apiVersion: v1
kind: ResourceQuota
metadata:
  name: storageos-critical-pods
  namespace: storageos
  labels:
    app: storageos
    app.kubernetes.io/component: operator
spec:
  hard:
    pods: 100
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-cluster-critical
      - system-node-critical