name: build

on: [push, pull_request]

jobs:
  test:
    name: build and test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Build kubectl-storageos
        run: make build
