name: Deploy to preprod cluster

on:
  workflow_dispatch:
    # Enable manual trigger of this action.
    inputs:
      project:
        description: Google Cloud project
        default: "portal-preprod-331817"
        required: true
      zone:
        description: Target zone
        default: "europe-west1-b"
        required: true
      cluster:
        description: Target cluster
        default: "eng"
        required: true
      extraFlags:
        description: Extra flags for the installer (default --skip-stos-cluster --wait --stack-trace)
        default: ""
        required: false

jobs:
  publish-feature-image:
    runs-on: ubuntu-latest
    name: Update StorageOS on dev cluster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: Persist Service account key
        run: echo -n '${{ secrets.GOOGLE_PREPROD_SA_KEY }}' > ${{ github.event.inputs.project }}.json
      - name: Fetch Kubeconfig
        run: ./hack/fetch-kube-congif.sh
        env:
          KEY_FILE: ${{ github.event.inputs.project }}.json
          ZONE: ${{ github.event.inputs.zone }}
          CLUSTER: ${{ github.event.inputs.cluster }}
          PROJECT: ${{ github.event.inputs.project }}
      - name: Build plugin
        run: make _build
      - name: Update StorageOS deployment
        run: ./hack/upgrade-cluster.sh
        env:
          EXTRA_FLAGS: ${{ github.event.inputs.extraFlags }}
