name: Release Version
on:
  push:
    tags:      
      - "v*"

jobs:
  auto-release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build operator manifests
        run: make fetch-latest-operator-manifests
        env:
          OPERATOR_DIR: specs
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --config .github/.goreleaser-release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
